#ifndef _AMEBAD2_ZB_INT_TEST_H_
#define _AMEBAD2_ZB_INT_TEST_H_

#define ZIGBEE_PURE_REG			(ZIGBEE_REG_BASE+0x1C00)
#define ZIGBEE_ISR 				0xC
#define ZIGBEE_IMR 				0x10
#define ZB2WL_MAILBOX_REG 		0x1110
#define WL2ZB_MAILBOX_REG 		0x1114

#endif
