#ifndef _AMEBA_GPIO_TEST_H_
#define _AMEBA_GPIO_TEST_H_

typedef struct {
	GPIO_TypeDef *GPIOx;
	IRQn_Type IrqNum;
} GPIO_DevTable;

typedef enum _GPIO_TEST_INT_TYPE_ {
	GPIO_TEST_INT_EDGE_RISING = 0,
	GPIO_TEST_INT_EDGE_FALLING,
	GPIO_TEST_INT_EDGE_BOTH,
	GPIO_TEST_INT_LEVEL_HIGH,
	GPIO_TEST_INT_LEVEL_LOW,

	GPIO_TEST_INT_MAX,
} GPIO_TEST_INT_TYPE, *PGPIO_TEST_INT_TYPE;

#define GPIO_PINNAME(PORT, PIN)			(((PORT) << 5) | ((PIN) & 0x1F))

#endif
