#ifndef _AMEBA_GPIO_TEST_H_
#define _AMEBA_GPIO_TEST_H_

typedef struct {
	GPIO_TypeDef *GPIOx;
	IRQn_Type IrqNum;
} GPIO_DevTable;

typedef enum _GPIO_TEST_INT_TYPE_ {
	GPIO_TEST_INT_EDGE_RISING = 0,
	GPIO_TEST_INT_EDGE_FALLING,
	GPIO_TEST_INT_EDGE_BOTH,
	GPIO_TEST_INT_LEVEL_HIGH,
	GPIO_TEST_INT_LEVEL_LOW,

	GPIO_TEST_INT_MAX,
} GPIO_TEST_INT_TYPE, *PGPIO_TEST_INT_TYPE;

typedef enum _PAD_TEST_TYPE_ {
	PAD_EST_NORMAL_NOPULL = 0,
	PAD_EST_NORMAL_PU,
	PAD_EST_NORMAL_PD,
	PAD_EST_SLEEP_NOPULL,
	PAD_EST_SLEEP_PU,
	PAD_EST_SLEEP_PD,

	PAD_TEST_TYPE_MAX,
} PAD_TEST_TYPE, *PPAD_TEST_TYPE;


#endif
